### PR TITLE
fix: bigger buttons on the mobile site (#205)

### LINKED ISSUE #205: Bigger buttons on the mobile site
The "sign up", "become a mentor" and the menu button should be bigger on the mobile. The minimum required hover area of the element is 40x40px.

Screenshot_20210826_132035

### PR DESCRIPTION
**Pull request by lagdush**
Closes #205

### CODE REVIEW

**Review by wierzbka10 — COMMENTED** [review]
Min hit area should be 40x40px, now menu icon have 32x32px and buttons have 32px high - size sm, shoud be md.

**Review by Veryyapeee — APPROVED** [review]

**Comment by lagdush** [comment]
> Min hit area should be 40x40px, now menu icon have 32x32px and buttons have 32px high - size sm, shoud be md.
@wierzbka10 I understand this rule, but with the same button layout as we have, if the button size is larger, the entire page layout will be broken on the iPhone 5s, 6 and X. It will be ok for the iPhone 6 plus.

File: packages/website/src/components/Navbar/Navbar.tsx [hunk 1]
```diff
@@ -24,11 +25,16 @@ export const Navbar = () => {
         position="relative"
       >
         {baseNavbar}
-        <Flex>
-          <Button size={buttonSize} mr="12px" onClick={() => openModal('mentor')}>
+        <Flex overflow="hidden">
+          <Button fontSize={isSmallerThan370px ? 'xs' : 'md'} size="md" mr="12px" onClick={() => openModal('mentor')}>
```
Comment (KonradSzwarc) [inline packages/website/src/components/Navbar/Navbar.tsx:29]: 🤔 We shouldn't modify the font size of our buttons as it creates inconsistency in our design system

**Review by KonradSzwarc — CHANGES_REQUESTED** [review]

**Comment by wierzbka10** [comment]
@lagdush Could you show me in the video how it looks with larger buttons?

**Comment by wierzbka10** [comment]
> 
> 
> > Min hit area should be 40x40px, now menu icon have 32x32px and buttons have 32px high - size sm, shoud be md.
> > @wierzbka10 I understand this rule, but with the same button layout as we have, if the button size is larger, the entire page layout will be broken on the iPhone 5s, 6 and X. It will be ok for the iPhone 6 plus.
> > I changed the font size on the smallest phones, check if it can stay that way.

@lagdush Could you show me in the video how it looks with larger buttons?

**Comment by lagdush** [comment]
> > > Min hit area should be 40x40px, now menu icon have 32x32px and buttons have 32px high - size sm, shoud be md.
> > > @wierzbka10 I understand this rule, but with the same button layout as we have, if the button size is larger, the entire page layout will be broken on the iPhone 5s, 6 and X. It will be ok for the iPhone 6 plus.
> > > I changed the font size on the smallest phones, check if it can stay that way.
> 
> @lagdush Could you show me in the video how it looks with larger buttons?


https://user-images.githubusercontent.com/38866668/131379458-bd887124-3754-4028-aee4-b23fd92c2839.mov

File: packages/website/src/components/Navbar/Navbar.tsx [hunk 2]
```diff
@@ -24,12 +25,12 @@ export const Navbar = () => {
         position="relative"
       >
         {baseNavbar}
-        <Flex>
-          <Button size={buttonSize} mr="12px" onClick={() => openModal('mentor')}>
+        <Flex overflow="hidden">
```
Comment (KonradSzwarc) [inline packages/website/src/components/Navbar/Navbar.tsx:28]: ❓ Why do we need overflow to be hidden here?

Comment (lagdush) [reply packages/website/src/components/Navbar/Navbar.tsx:28]: It seems to me that with overflow hidden, larger buttons do not destroy the page layout. This can be seen especially in the curriculum section of the iPhone 6 mobile view.

Comment (lagdush) [reply packages/website/src/components/Navbar/Navbar.tsx:28]: But I can see that after deployment, the page looks different than for me locally.

**Review by wierzbka10 — CHANGES_REQUESTED** [review]
I designed how shoud look buttons and hamburger button in the navigation on the different mobile sizes. On every screens smaller than 560px wide buttons "zapisz się na kurs" and "zostań mentorem" are inside drop-down menu, but on screens bigger or equel than 560px the buttons are in the navigation. Buttons in both are of the size md (40px high).

Link to figma: https://www.figma.com/file/ur0KLA9ZOtiodrAmpXrxh9/CodersCamp-app-and-website?node-id=2466%3A5013

**Review by wierzbka10 — CHANGES_REQUESTED** [review]
buttons should be align to right, not centered.
buttons

**Review by wierzbka10 — APPROVED** [review]

**Review by hoolek77 — APPROVED** [review]

**Review by KonradSzwarc — APPROVED** [review]
