### PR TITLE
fix(website): add cancel icon to modals

### LINKED ISSUE #242: Add cancel icons in modals
Modal

### PR DESCRIPTION
**Pull request by hoolek77**
Closes #242

### CODE REVIEW

File: packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx [hunk 1]
```diff
@@ -36,8 +40,16 @@ export const RecruitmentModal = ({ isOpen, config, onClose, modalType }: Recruit
         boxShadow="large"
         textAlign="center"
       >
+        <IconButton
```
Comment (KonradSzwarc) [inline packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx:43]: 🤔 Closing icon is the first element that gets focused when you open the modal. I'm no sure if it should work that way. Maybe it would be better if we put autofocus to the name input.

File: packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx [hunk 2]
```diff
@@ -24,6 +26,8 @@ interface RecruitmentModalProps {
 export const RecruitmentModal = ({ isOpen, config, onClose, modalType }: RecruitmentModalProps) => {
   const modalContentPaddings = useBreakpointValue({ base: '32px 16px 16px 32px', md: '56px 64px 64px 64px' } as const);
   const modalBodyMarginBottom = useBreakpointValue({ base: '16px', lg: '32px' } as const);
+  const modalCloseIconSize = useBreakpointValue({ base: 'sm', md: 'lg' } as const);
```
Comment (KonradSzwarc) [inline packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx:29]: 🤔 If I remember correctly, all clickable elements should be at least 40x40px. Small icon button has 32x32px

File: packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx [hunk 3]
```diff
@@ -24,6 +26,8 @@ interface RecruitmentModalProps {
...
+  const modalHeaderTextMargin = useBreakpointValue({ base: '32px', md: '60px' } as const);
```
Comment (KonradSzwarc) [inline packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx:30]: 🤔 For large screens we use only values that are divisible by 8, so 64px for the `md` margin will be better

File: packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx [hunk 4]
```diff
@@ -36,8 +40,16 @@ export const RecruitmentModal = ({ isOpen, config, onClose, modalType }: Recruit
         boxShadow="large"
         textAlign="center"
       >
+        <IconButton
+          icon={<SolidCloseIcon />}
+          aria-label="Close modal button"
+          variant="ghost"
+          style={{ position: 'absolute', top: 12, right: 12 }}
```
Comment (KonradSzwarc) [inline packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx:47]: ❓ Do you need the `style` attribute here? Cannot it be achieved by passing those style properties as props?

File: packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx [hunk 5]
```diff
@@ -36,8 +40,16 @@ export const RecruitmentModal = ({ isOpen, config, onClose, modalType }: Recruit
         boxShadow="large"
         textAlign="center"
       >
+        <IconButton
+          icon={<SolidCloseIcon />}
+          aria-label="Close modal button"
```
Comment (KonradSzwarc) [inline packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx:45]: 🤔 Labels are for people so they should be in website language

File: packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx [hunk 6]
```diff
@@ -36,8 +40,16 @@ export const RecruitmentModal = ({ isOpen, config, onClose, modalType }: Recruit
...
+          variant="ghost"
+          style={{ position: 'absolute', top: 12, right: 12 }}
+          size={modalCloseIconSize}
+          onClick={onClose}
+        />
         <ModalHeader p={0}>
-          <Typography as="h2" size="4xl" weight="extrabold" color="gray.900" style={{ whiteSpace: 'pre-line' }}>
+          <Typography as="h2" size="4xl" weight="extrabold" color="gray.900" marginX={modalHeaderTextMargin}>
```
Comment (KonradSzwarc) [inline packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx:52]: 🙃 You can use `mx` as a shortcut

File: packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx [hunk 7]
```diff
@@ -1,5 +1,6 @@
 import React from 'react';
 
+import { IconButton } from '@coderscamp/ui/components/IconButton';
```
Comment (KonradSzwarc) [inline packages/website/src/components/RecruitmentModal/RecruitmentModal.tsx:3]: ❓ Chakra has its own button for closing modals called `AlertDialogCloseButton`. Cannot we use it here?

**Review by KonradSzwarc — CHANGES_REQUESTED** [review]

**Review by wierzbka10 — APPROVED** [review]

**Review by Veryyapeee — APPROVED** [review]

**Review by KonradSzwarc — APPROVED** [review]
