### PR TITLE
fix(website): react headroom - navigation (#202)

### LINKED ISSUE #202: React headroom - navigation
When you scroll down, navigation shoud slide out of view and slide back in when scrolling up like on this site https://kyleamathews.github.io/react-headroom/, beacuse it lets user in easy way come back to button with which he can sign up to the Coderscamp.

### PR DESCRIPTION
**Pull request by KrystianKjjk**
Closes #202

### CODE REVIEW

File: packages/website/src/components/Navbar/Navbar.tsx [hunk 1]
```diff
@@ -8,13 +9,22 @@ import { useRecruitmentModal } from '@/components/RecruitmentModal';
 
 import { DesktopBaseNavbar, MobileBaseNavbar } from './BaseNavbar';
 
+const headroomStyles = {
+  zIndex: 1000,
+  background: 'rgba(255, 255, 255)',
+  boxShadow: '1px 1px 1px rgba(0,0,0,0.25)',
```
Comment (lagdush) [inline packages/website/src/components/Navbar/Navbar.tsx:15]: ❓ Do we need box shadow here? I've noticed that in the mobile view, navigating behaves a bit strange.

https://user-images.githubusercontent.com/38866668/131527225-2ced7716-d51b-48ee-b843-cf2a0123b478.mov

File: packages/website/package.json [hunk 2]
```diff
@@ -16,12 +16,14 @@
...
     "react": "17.0.2",
     "react-dom": "17.0.2",
+    "react-headroom": "3.1.1",
     "react-hook-form": "7.14.0",
     "swiper": "7.0.1"
   },
   "devDependencies": {
     "@types/nodemailer": "6.4.4",
     "@types/react": "17.0.19",
+    "@types/react-headroom": "^2.2.2",
```
Comment (KonradSzwarc) [inline packages/website/package.json:26]: 🤔 We should pin all packages versions

File: packages/website/src/components/Navbar/Navbar.tsx [hunk 3]
```diff
@@ -8,13 +9,22 @@ import { useRecruitmentModal } from '@/components/RecruitmentModal';
 
 import { DesktopBaseNavbar, MobileBaseNavbar } from './BaseNavbar';
 
+const headroomStyles = {
+  zIndex: 1000,
+  background: 'rgba(255, 255, 255)',
```
Comment (KonradSzwarc) [inline packages/website/src/components/Navbar/Navbar.tsx:14]: 🤔 You should use values from our theme for `backgrond` and `boxShadow`. Also, box-shadow shouldn't appear when the navbar is in its initial position (at the top).

**Review by KonradSzwarc — CHANGES_REQUESTED** [review]

File: packages/website/src/components/Navbar/Navbar.tsx (hunk 3 above)
Comment (wierzbka10) [reply packages/website/src/components/Navbar/Navbar.tsx:14]: I agree with Konrad and it looks better when is larger box-shadow, beacuse now it looks like simply line. In figma it's shadow style "large".

Comment (KrystianKjjk) [reply packages/website/src/components/Navbar/Navbar.tsx:14]: @KonradSzwarc @wierzbka10  styling with colors like "gray.500" would not work, because its  not chakra component. I tried to connect chakra with headroom but it didn’t t work properly, so 'shadow="lg" ' does not work. 

What value of boxShadow should I use? I don't see it on figma nowhere 🤔

Comment (wierzbka10) [reply packages/website/src/components/Navbar/Navbar.tsx:14]: @KrystianKjjk This shadow consists of two shadows:
shadow1
shadow2

**Review by lagdush — CHANGES_REQUESTED** [review]
There is some bug with AboutTestimonials and Projects sections
https://user-images.githubusercontent.com/38866668/131892414-c393b86a-6e5e-4185-bf3c-f76e91481127.mov

**Comment by KrystianKjjk** [comment]
> There is some bug with AboutTestimonials and Projects sections
> https://user-images.githubusercontent.com/38866668/131892414-c393b86a-6e5e-4185-bf3c-f76e91481127.mov

zIndex used in wrong place 
Now should be good :)

**Review by lagdush — APPROVED** [review]

**Review by wierzbka10 — APPROVED** [review]

**Review by KonradSzwarc — APPROVED** [review]
